# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0003_auto_20160828_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_color',
            field=models.IntegerField(choices=[(1, 'white'), (2, 'green')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
