# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0005_auto_20160829_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gear.Item'),
        ),
    ]
