# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0009_auto_20160829_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.IntegerField(choices=[(1, 'white'), (2, 'green'), (3, 'blue'), (4, 'purple'), (5, 'orange')], default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
