# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20160829_0146'),
        ('gear', '0010_auto_20160829_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='GearStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gear.Item')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Stat')),
            ],
        ),
    ]
