# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0011_gearstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='equippable',
            field=models.BooleanField(default=False),
        ),
    ]
