# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0013_auto_20160903_0330'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='item',
            order_with_respect_to=None,
        ),
    ]
