# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0023_auto_20160905_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gear.Recipe'),
        ),
    ]
