# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0027_auto_20160905_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gear.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.IntegerField(choices=[(1, 'White'), (2, 'Green'), (3, 'Blue'), (4, 'Purple'), (5, 'Orange')], default=1),
        ),
    ]
