# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0031_auto_20160910_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearstat',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='gear.Item'),
        ),
    ]
