# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0019_quest_color'),
        ('stats', '0002_auto_20160829_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_benefit', models.BooleanField(default=False)),
                ('hero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stat_users', to='heroes.Hero')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_users', to='stats.Stat')),
            ],
        ),
    ]
