# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_equipper'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipper',
            new_name='Stat_User',
        ),
    ]
