# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20161118_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat_user',
            name='all_benefit',
        ),
        migrations.AddField(
            model_name='stat',
            name='all_benefit',
            field=models.BooleanField(default=False),
        ),
    ]
