# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-27 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_stat_user_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
