# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0019_quest_color'),
        ('runes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equippers', to='runes.Collection')),
                ('hero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equippers', to='heroes.Hero')),
            ],
        ),
    ]
