# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(default='Chapter: ', max_length=200, null=True, unique=True),
        ),
    ]
