# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0004_auto_20160909_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage', to='drops.Chapter'),
        ),
    ]
