# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0005_auto_20160909_0015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drops',
            new_name='Drop',
        ),
    ]
