# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0006_auto_20160909_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='chapter',
            field=models.IntegerField(choices=[(1, 'Chapter 1: hsfs'), (2, 'Chapter 2: kiusfs'), (3, 'Chapter 3: musfs'), (4, 'Chapter 4: thrht'), (5, 'Chapter 5: rgrddg')], default=1),
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
