# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0007_auto_20160909_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
                ('cost', models.IntegerField(null=True)),
                ('minlevel', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stage',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='cost',
        ),
        migrations.AddField(
            model_name='chapter',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='drops.Stage'),
        ),
    ]
