# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0008_auto_20160910_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='stage',
        ),
    ]
