# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0010_stage_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='chapter',
        ),
        migrations.AddField(
            model_name='chapter',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='drops.Stage'),
        ),
    ]
