# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 00:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0012_auto_20160911_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drop',
            old_name='drops',
            new_name='item',
        ),
    ]
