# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0013_auto_20160928_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drop',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drops', to='gear.Item'),
        ),
    ]
