# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0014_auto_20160928_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
