# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rarity',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroes.Hero'),
        ),
    ]
