# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0012_item_equippable'),
        ('heroes', '0003_auto_20160831_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='rarity',
            name='gear1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gear.Item'),
        ),
    ]
