# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0012_item_equippable'),
        ('heroes', '0004_rarity_gear1'),
    ]

    operations = [
        migrations.AddField(
            model_name='rarity',
            name='gear2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gear2', to='gear.Item'),
        ),
        migrations.AlterField(
            model_name='rarity',
            name='gear1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gear1', to='gear.Item'),
        ),
    ]
