# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0006_auto_20160903_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rarity',
            name='color',
            field=models.IntegerField(choices=[(1, 'White'), (2, 'Green'), (3, 'Blue'), (4, 'Purple'), (5, 'Orange')], default=1),
        ),
    ]
