# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0007_auto_20160904_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rarity',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rarity', to='heroes.Hero'),
        ),
    ]
