# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0029_auto_20160905_1908'),
        ('heroes', '0009_auto_20160905_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, null=True, unique=True)),
                ('quantity', models.IntegerField(null=True)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest', to='heroes.Hero')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gear.Item')),
            ],
        ),
    ]
