# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0029_auto_20160905_1908'),
        ('heroes', '0010_quest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='stage',
        ),
        migrations.AddField(
            model_name='quest',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='sacrifice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gear.Item'),
        ),
    ]
