# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 00:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0011_auto_20160907_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='name',
        ),
    ]
