# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0013_auto_20160907_0208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='quest',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='rarity',
            options={'ordering': ['color', 'level']},
        ),
    ]
