# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0014_auto_20160907_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rarity',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
