# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 04:08
from __future__ import unicode_literals

from django.db import migrations
from heroes.models import Rarity

def updateLevels(apps, schema_editor):
	if not schema_editor.connection.alias == 'default':
		return
	rarities = Rarity.objects.filter(level=None)
	for rarity in rarities:
		rarity.level = 0
		rarity.save()

class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0015_auto_20160907_0402'),
    ]

    operations = [
		migrations.RunPython(updateLevels)
    ]

