# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0016_auto_20160907_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='image',
            field=models.ImageField(height_field='height', null=True, upload_to='heroes', width_field='width'),
        ),
    ]
