# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0017_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
