# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0018_auto_20160909_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='color',
            field=models.IntegerField(choices=[(5, 'Orange')], default=5),
        ),
    ]
