# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-27 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_stat_primary'),
        ('heroes', '0019_quest_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='primary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Stat'),
        ),
    ]
